DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'grisha') THEN
CREATE ROLE grisha WITH LOGIN PASSWORD 'grisha123';
END IF;
END $$;

GRANT CONNECT ON DATABASE avito_db TO grisha;
GRANT USAGE ON SCHEMA public TO grisha;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grisha;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO grisha;